apiVersion: v1
kind: Service
metadata:
  name: cardiology-api-service
  namespace: cardiology-assistant
spec:
  type: ClusterIP
  selector:
    app: cardiology-api
  ports:
    - port: 8000
      targetPort: 8000
